### PR TITLE
Add CI/CD

### PR DESCRIPTION
**Pull request by andrew-nowak**
## What does this change?

Crossword uploader had no CI/CD implementation. Deploying new versions involved running a bash script, which would build and upload the lambda locally.

Follow up PRs will do upgrades of dependencies, scala version, sbt, etc.

## How to test

Deploy to CODE from riffraff (flexible::crossword-uploader). Throw some files into the bucket on code. Do the uploaders function correctly?

## How can we measure success?

CI & CD 🎉 Less barriers to developing and upgrading, etc.

- [x] Deployed and tested on CODE

### CODE REVIEW

**Review by jonathonherbert — APPROVED** [review]
Deployed to CODE, can see it running but I couldn't get a crossword to upload [without OoM errors 🤔](https://logs.gutools.co.uk/s/editorial-tools/goto/6c2fb7e0-7a12-11ed-8847-f51dd22748b2)

**Review by jonathonherbert — CHANGES_REQUESTED** [review]
(that was not meant to be an approve!)

**Comment by andrew-nowak** [comment]
@jonathonherbert hmm that does look odd - but it seems you have deployed #28 rather than this branch? which I hadn't tested yet!

**Review by jonathonherbert — APPROVED** [review]
Oops, yes – redeployed and all looks well ✨

**Pull request merged**
